{
  "pathstPathwCode": "G54",
  "taskId": 1,
  "tasktId": 1,
  "taskCliId": 1,
  "taskRefId": 1,
  "taskSgrId": 1,
  "taskPatId": 1,
  "tasktTypeEliId": 1,
  "tasktName": "Admit patient",
  "tasktQueCode": "1001",
  "tasktTypeEliText": "Procedure",
  "tasktApptSpecialityEliId": 1,
  "tasktApptRegionEliId": 1,
  "tasktApptReasonEliId": 1,
  "tasktApptReasonEliText": "Audiology consultation",
  "tasktApptClinicTypeEliId": 1,
  "tasktApptClinicLocationEliId": 1,
  "tasktDescription": "Admit patient",
  "tasktAssignedToUsergroup": "david",
  "tasktDueIn": 10,
  "tasktDueUnit": "months",
  "tasktForSelectedPatient": 1,
  "tasktTaskForCurrentUser": 1,
  "tasktRecurring": 1,
  "tasktShowAlertForTask": 1,
  "tasktRecurringIn": 1,
  "tasktRecurringUnit": "years",
  "tasktRecurringTimeInterval": 5,
  "tasktTaskActionToPerform": "review",
  "tasktAlertTypeCritical": 1,
  "tasktCreateInvoice": 1,
  "tasktMedDose": "10mg",
  "tasktMedFrequency": "2",
  "tasktMedRoute": "oral",
  "tasktMedDuration": "1",
  "tasktProcedureType": "emergency",
  "tasktProcedureSite": "right",
  "taskdCategoryStatus": "requested",
  "tasktGender": "m",
  "taskGenderSpecific": 0,
  "tasktAgeRangeStart": 10,
  "tasktAgeRangeEnd": 20,
  "taskDueDate": "13/10/2024",
  "taskDueTime": "10:15",
  "taskAgeSpecific": 0,
  "taskNotes": "string",
  "taskdAssignedToUsgName": "Read-Only",
  "taskdAlertTrigger": "due",
  "taskAssignedToUsername": "string",
  "additionallySendAlertTo": "patient",
  "additionallySendAlertUsing": "email",
  "alertPacrId": 1,
  "tasktQueType": "string",
  "tasktLocalCode null,
  "taskStatus": "1",
  "taskPriority": "1",
  "taskWorId": 1,
  "taskPworId": 1,
  "taskStartDate": "01/07/2024",
  "taskpptId": 1,
  "taskTemplateSpecialityLinkingJson": [
    {
      "tatsplSpecialityEliCode": "123",
      "tatsplSpecialityEliText": "Cardiology"
    }
  ],
  "tasktType": "default",
  "tasktTypeValue": "Cardiology",
  "deleteTatsplId": 1
}